[package]
name = "chaptera-pub-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "pub"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
sha2.workspace = true
pub-model = { path = "../../vendor/producer-a/crates/pub-model" }
pub-reader = { path = "../../vendor/producer-a/crates/pub-reader" }
