param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Import-Module (Join-Path $PSScriptRoot "PubRuntime.psm1") -Force

$PbFilePublication = 1
$MsoFalse = 0
$MsoShapeRectangle = 1
$TargetTag = "FALSE_OMISSION_TARGET"

function Close-GeneratedDocument {
    param($Document, $Application)
    if ($null -ne $Document) {
        try { $Document.Close() } catch {}
        try { [void][System.Runtime.InteropServices.Marshal]::FinalReleaseComObject($Document) } catch {}
    }
    Close-PubPublisherApplication $Application
}

function Get-OracleTagValue {
    param([Parameter(Mandatory = $true)]$Shape)
    try {
        for ($i = 1; $i -le [int]$Shape.Tags.Count; $i++) {
            $tag = $Shape.Tags.Item($i)
            if ([string]$tag.Name -eq "PUB_ORACLE_ID") {
                return [string]$tag.Value
            }
        }
    } catch { return $null }
    return $null
}

function Find-Target {
    param([Parameter(Mandatory = $true)]$Document)
    $matches = @()
    for ($pageIndex = 1; $pageIndex -le [int]$Document.Pages.Count; $pageIndex++) {
        $page = $Document.Pages.Item($pageIndex)
        for ($shapeIndex = 1; $shapeIndex -le [int]$page.Shapes.Count; $shapeIndex++) {
            $shape = $page.Shapes.Item($shapeIndex)
            if ((Get-OracleTagValue -Shape $shape) -eq $TargetTag) {
                $matches += $shape
            }
        }
    }
    if ($matches.Count -ne 1) {
        throw "Expected exactly one PUB_ORACLE_ID=$TargetTag; found $($matches.Count)"
    }
    return $matches[0]
}

if (Test-Path -LiteralPath $OutputPath) {
    throw "Refusing to overwrite existing fixture: $OutputPath"
}

$parent = Split-Path -Parent $OutputPath
if ($parent) {
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
}

$application = $null
$document = $null
try {
    $application = New-PubPublisherApplication
    $document = $application.Documents.Add()
    $page = $document.Pages.Item(1)
    $shape = $page.Shapes.AddShape($MsoShapeRectangle, 73, 91, 181, 103)
    $shape.Tags.Add("PUB_ORACLE_ID", $TargetTag) | Out-Null
    $shape.Fill.Solid()
    $shape.Fill.ForeColor.RGB = 0x336699
    $shape.Line.ForeColor.RGB = 0x663399
    $shape.Fill.Visible = $MsoFalse
    $shape.Line.Visible = $MsoFalse
    $document.SaveAs($OutputPath, $PbFilePublication, $false)
} finally {
    Close-GeneratedDocument -Document $document -Application $application
}

$application = $null
$document = $null
try {
    $application = New-PubPublisherApplication
    $document = $application.Open($OutputPath, $true, $false)

    if ([int]$document.Pages.Count -ne 1) {
        throw "Fixture requires exactly one page"
    }
    $page = $document.Pages.Item(1)
    if ([int]$page.Shapes.Count -ne 1) {
        throw "Fixture requires exactly one top-level shape"
    }

    $shape = Find-Target -Document $document
    if ([int]$shape.Fill.Visible -ne $MsoFalse -or [int]$shape.Line.Visible -ne $MsoFalse) {
        throw "Fixture reopen visibility contract failed"
    }

    $geometry = @(
        [double]$shape.Left,
        [double]$shape.Top,
        [double]$shape.Width,
        [double]$shape.Height
    )
    $expected = @(73.0, 91.0, 181.0, 103.0)
    for ($i = 0; $i -lt $geometry.Count; $i++) {
        if ([Math]::Abs($geometry[$i] - $expected[$i]) -gt 0.001) {
            throw "Fixture geometry drift at index ${i}: $($geometry[$i]) != $($expected[$i])"
        }
    }
} finally {
    Close-GeneratedDocument -Document $document -Application $application
}

$record = Get-PubFileRecord $OutputPath
[ordered]@{
    fixture_id = "FALSE-OMISSION-SHAPE-BASE"
    experiment_id = "FALSE-OMISSION-01"
    oracle_tag = $TargetTag
    fill_visible = 0
    line_visible = 0
    left = 73
    top = 91
    width = 181
    height = 103
    file = $record
    evidence_boundary = "Generated bytes are preparation only until version-pinned native execution and downstream raw attribution."
} | ConvertTo-Json -Depth 8
