[package]
name = "pub-presentation-profile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["canonical-page-ids"]
canonical-page-ids = ["dep:pub-model"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
pub-model = { path = "../pub-model", optional = true }

[[bin]]
name = "carlton-presentation-profile"
path = "src/bin/carlton-presentation-profile.rs"
